name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Create env file
        run: |
          touch .env
          echo CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }} >> .env
          echo CONTENTFUL_ENVIRONMENT=${{ secrets.CONTENTFUL_ENVIRONMENT }} >> .env
          echo CONTENTFUL_TOKEN=${{ secrets.CONTENTFUL_TOKEN }} >> .env

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRUFFLESUITE_COM_GH_API_USERNAME: ${{ secrets.TRUFFLESUITE_COM_GH_API_USERNAME }}
          TRUFFLESUITE_COM_GH_API_KEY: ${{ secrets.TRUFFLESUITE_COM_GH_API_KEY }}
